app/models.py
from app import db
from datetime import datetime

class ApiConfig(db.Model):
    __tablename__ = "apiconfig"

    id = db.Column(db.Integer, primary_key=True)
    backup_directory = db.Column(db.String(), nullable=False, unique=True)

    def __repr__(self):
        return "<YANBT ApiConfig {}>".format(self.id)

    def as_dict(self):
        return {
            "backup_directory": self.backup_directory
        }

class User(db.Model):
    __tablename__ = "user"

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(), nullable=False)
    password = db.Column(db.String(), nullable=False)
    devices = db.relationship("Device", backref="user", lazy='dynamic')

    def __init__(self, username, password, **kwargs):
        self.username = username
        self.password = password

    def __repr__(self):
        return "<YANBT User {}>".format(self.username)

    def as_dict(self, show_password=True):
        return {
            "id": self.id,
            "username": self.username,
            "password": self.password if show_password else "--hidden--",
            "devices": [_device.id for _device in self.devices]
        }

class Device(db.Model):
    __tablename__ = "device"

    id = db.Column(db.Integer, primary_key=True)
    friendly_name = db.Column(db.String)
    ip = db.Column(db.String, nullable=False)
    port = db.Column(db.Integer)
    netmiko_driver = db.Column(db.String, nullable=False)
    authentication_user = db.Column(db.Integer, db.ForeignKey("user.id"))
    config_command = db.Column(db.String)
    pre_commands = db.Column(db.String)
    assigned_group = db.Column(db.String, db.ForeignKey("group.folder_path"))
    description = db.Column(db.String)
    notes = db.Column(db.String)

    def __repr__(self):
        return "<YANBT Device {}>".format(self.id)

    def as_dict(self):
        return {
            "id": self.id,
            "friendly_name": self.friendly_name,
            "ip": self.ip,
            "port": self.port,
            "netmiko_driver": self.netmiko_driver,
            "authentication_user": self.authentication_user,
            "config_command": self.config_command,
            "pre_commands": self.pre_commands,
            "assigned_group": Group.query.get(self.assigned_group).folder_path if Group.query.get(self.assigned_group) else None,
            "description": self.description,
            "notes": self.notes
        }

    def as_dict_basic(self):
        return {
            "id": self.id,
            "friendly_name": self.friendly_name,
            "ip": self.ip,
            "port": self.port
        }

class Group(db.Model):
    __tablename__ = "group"

    name = db.Column(db.String, nullable=False)
    folder_path = db.Column(db.String, nullable=False, primary_key=True)
    is_root = db.Column(db.Boolean)
    is_child = db.Column(db.Boolean)
    child_root = db.Column(db.Integer)
    description = db.Column(db.String)
    devices = db.relationship("Device", backref="device", lazy='dynamic')
    backup_job = db.relationship("BackupJob", backref="backupjob", lazy='dynamic')

    def __repr__(self):
        return "<YANBT Group {}>".format(self.name)

    def as_dict(self):
        return {
            "name": self.name,
            "folder_path": self.folder_path,
            "description": self.description,
            "devices": [_device.as_dict_basic() for _device in self.devices] if self.devices else []
        }

class BackupJob(db.Model):
    __tablename__ = "backupjob"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, nullable=False)
    description = db.Column(db.String)
    assigned_group = db.Column(db.Integer, db.ForeignKey("group.folder_path"))
    active = db.Column(db.Boolean)
    start_date_time = db.Column(db.String)
    end_date_time = db.Column(db.String)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    job_occur = db.Column(db.String)
    job_start_time = db.Column(db.String)

    def __repr__(self):
        return "<YANBT BackupJob {}>".format(self.id)

    def as_dict():
        return {
            "id": self.id,
            "name": self.name,
            "description": self.description,
            "assigned_group": Group.query.get(self.assigned_group).folder_path if self.assigned_group else None,
            "active": self.active,
            "start_date_time": self.start_date_time,
            "end_date_time": self.end_date_time,
            "created_at": self.created_at,
            "job_occur": self.job_occur,
            "job_start_time": self.job_start_time
        }

    

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SelectField, SubmitField
from wtforms.validators import DataRequired
from netmiko.ssh_dispatcher import CLASS_MAPPER

class AddUser(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Add User')

class AddDevice(FlaskForm):
    friendly_name = StringField('Friendly Name', validators=[DataRequired()])
    ip = StringField('IP Address', validators=[DataRequired()])
    netmiko_driver = SelectField('Netmiko Driver', choices=[driver for driver in CLASS_MAPPER.keys()], validators=[DataRequired()])
    authentication_user = SelectField('User', choices=[], validators=[DataRequired()])
    submit = SubmitField('Add Device')

app/__init__.py
from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy
from config import Config

app = Flask(__name__)
app.config.from_object(Config)

db = SQLAlchemy(app)

from app.views import (
    backup_jobs,
    dashboard,
    devices,
    settings,
    users,
    groups
)

from app.views.api import (
    api_users,
    api_devices,
    api_tools,
    api_config,
    api_groups,
    api_backupjob
)

from app import models

db.create_all()

# Preload additional app config (from database) - Need to find a better way of doing this...
with app.app_context():
    try:
        Config.load_local_config()
    except:
        print("Error trying to load local config...")

    #Sync database groups with folders
    api_tools.database_sync()

app.register_blueprint(backup_jobs.bp)
app.register_blueprint(dashboard.bp)
app.register_blueprint(devices.bp)
app.register_blueprint(settings.bp)
app.register_blueprint(users.bp)
app.register_blueprint(groups.bp)
app.register_blueprint(api_users.bp)
app.register_blueprint(api_devices.bp)
app.register_blueprint(api_tools.bp)
app.register_blueprint(api_config.bp)
app.register_blueprint(api_groups.bp)
app.register_blueprint(api_backupjob.bp)

app/views/backup_jobs.py
from flask import Blueprint, render_template

bp = Blueprint("backup_jobs", __name__, url_prefix="/backup_jobs")

@bp.route("/", methods=["GET"])
def index():
    return render_template("backup_jobs/index.html")

@bp.route("/new_job", methods=["GET"])
def new_job():
    return render_template("backup_jobs/new_job.html")

app/views/dashboard.py
from flask import Blueprint, render_template
from app.utilities import database_functions

bp = Blueprint("dashboard", __name__)

@bp.route("/", methods=["GET"])
def index():
    stats = database_functions.total_stats()
    return render_template("dashboard/index.html", stats=stats)

app/views/devices.py
from flask import Blueprint, render_template

bp = Blueprint("devices", __name__, url_prefix="/devices")

@bp.route("/", methods=["GET"])
def index():
    return render_template("devices/index.html")

@bp.route("/new_device", methods=["GET"])
def new_device():
    return render_template("devices/new_device.html")

app/views/groups.py
from flask import Blueprint, render_template

bp = Blueprint("groups", __name__, url_prefix="/groups")

@bp.route("/", methods=["GET"])
def index():
    return render_template("groups/index.html")

app/views/settings.py
from flask import Blueprint, render_template

bp = Blueprint("settings", __name__, url_prefix="/settings")

@bp.route("/", methods=["GET"])
def index():
    return render_template("settings/index.html")

app/views/users.py
from flask import Blueprint, render_template, request

bp = Blueprint("users", __name__, url_prefix="/users")

@bp.route("/", methods=["GET"])
def index():
    return render_template("users/index.html")

app/templates/backup_jobs/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Backup Jobs</h1>
<div class="row m-3">
    <div class="card col-12">
        <div class="p-3">
            <table class="table table-striped" id="backupJobsTable">
                <thead>
                    <th>Job ID</th>
                    <th>Name</th>
                    <th>Assigned Group</th>
                    <th>Active</th>
                    <th>Start Date/Time</th>
                    <th>End Date/Time</th>
                    <th></th>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
    <div class="col-12 mt-3">
        <a class="btn btn-primary btn-sm float-right" href="{{ url_for('backup_jobs.new_job') }}" role="button">Create Job</a>
    </div>
</div>
{% endblock %}

app/templates/backup_jobs/new_job.html
{% extends 'base.html' %}
{% block content %}
<h1>New Backup Job</h1>
<div class="row m-3">
    <div class="card col-12">
        <div class="p-3">
            <form>
                <div class="row">
                    <div class="form-group col-md-4">
                        <label for="name">Name*</label>
                        <input type="text" class="form-control" id="name" placeholder="Enter job name">
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-4">
                        <label for="description">Description</label>
                        <input type="text" class="form-control" id="description" placeholder="eg. Firewall HA Backup">
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-2">
                        <label for="groups">Group*</label>
                        <select class="form-control" id="groups">
                            <option />
                        </select>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-4">
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="enabled">
                            <label class="form-check-label" for="enabled">Enable Job</label>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-4">
                        <label for="occur">Occur</label>
                        <input type="text" class="form-control" id="occur" placeholder="eg. 1,1,1,1,1,0,0">
                        <small id="occurHelp" class="form-text text-muted">Mon,Tue,Wed,Thu,Fri,Sat,Sun - Use 0 to skip or 1 to backup. For example, backups only on Monday and Fridays will be: 1,0,0,0,1,0,0</small>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-4">
                        <label for="backupTime">Backup Time</label>
                        <input type="text" class="form-control" id="backupTime" placeholder="eg. 10:45">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="container-fluid">
    <h5>Debug Output</h5>
    <pre class="bg-light p-3" id="debugOutput">
    </pre>
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{{ url_for('static', filename='js/backup_jobs/new_job.js') }}"></script>
{% endblock %}

app/templates/base.html
<!doctype html>
<html lang="en">

<head>
<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Bootstrap CSS -->
	<!--<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"/>-->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/all.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/simple-sidebar.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/app.css') }}">
	{% block stylesheets %}
	{% endblock %}

	<title>{% block title %}{% endblock %} - YANBT</title>
</head>

<body>
	<div class="d-flex" id="wrapper">
		<!-- Sidebar -->
		<div class="bg-light border-right" id="sidebar-wrapper">
			<div class="sidebar-heading">Yet Another Network Backup Tool</div>
			<div class="list-group list-group-flush w-100">
				<a href="{{ url_for("dashboard.index") }}" class="list-group-item list-group-item-action bg-light">Dashboard</a>
				<a href="{{ url_for("backup_jobs.index") }}" class="list-group-item list-group-item-action bg-light">Backup Jobs</a>
				<a href="{{ url_for("users.index") }}" class="list-group-item list-group-item-action bg-light">Users</a>
				<a href="{{ url_for("devices.index") }}" class="list-group-item list-group-item-action bg-light">Devices</a>
				<a href="{{ url_for("groups.index") }}" class="list-group-item list-group-item-action bg-light">Groups</a>
				<a href="{{ url_for("settings.index") }}" class="list-group-item list-group-item-action bg-light">Settings</a>
			</div>
		</div>
		<!-- /#sidebar-wrapper -->

		{% for message in get_flashed_messages() %}
		<div class="flash">{{ message }}</div>
		{% endfor %}
		
		<!-- Page Content -->
		<div id="page-content-wrapper">
			<!-- Content Placeholder -->
			<div class="container-fluid p-5">{% block content %}{% endblock %}</div>
			<!-- End of Content -->
		</div>
	</div>

	<!-- Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
	
	<!-- Scripts Block -->
	{% block scripts %}{% endblock %}
	<!-- End of Scripts -->
</body>
</html>

app/templates/dashboard/index.html
{% extends 'base.html' %}

{% block stylesheets %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-treeview.css') }}">
{% endblock %}

{% block content %}
<h1>Dashboard</h1>
<div class="row">
    <div class="card col-12 p-4 mb-5">
        <div class="row">
            <div class="col-md-4 text-center">
                <h5>Current Users</h5>
                <div class="numberCircle">{{ stats.total_users }}</div>
            </div>
            <div class="col-md-4 text-center">
                <h5>Current Devices</h5>
                <div class="numberCircle">{{ stats.total_devices }}</div>
            </div>
            <div class="col-md-4 text-center">
                <h5>Active Jobs</h5>
                <div class="numberCircle">{{ stats.total_jobs }}</div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="container col-3">
        <h3>Backup Explorer</h3>
        <div class="card p-4 mb-5 mr-auto">
            <div id="tree"></div>
        </div>
    </div>
        <div class="container-fluid col-9">
        <h3>Config Viewer</h3>
        <div class="card">
            <pre class="bg-light m-1 p-3" style="height:1200px;" id="configViewer">
            </pre>
        </div>
    </div>
</div>

{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap-treeview.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/dashboard/dashboard_generic.js') }}"></script>
{% endblock %}

app/templates/devices/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Devices</h1>
<div class="row m-3">
    <div class="card col-12">
        <div class="p-3">
            <table class="table table-striped" id="devicesTable">
                <thead>
                    <th>#</th>
                    <th>Friendly Name</th>
                    <th>IP</th>
                    <th>Port</th>
                    <th>Netmiko Driver</th>
                    <th>User</th>
                    <th>Group</th>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
    <div class="col-12 mt-3">
        <a class="btn btn-primary btn-sm float-right" href="{{ url_for('devices.new_device') }}" role="button">New Device</a>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{{ url_for('static', filename='js/devices/devices_generic.js') }}"></script>
{% endblock %}

app/templates/devices/new_device.html
{% extends 'base.html' %}

{% block content %}
<h1>New Device</h1>
<div class="row m-3">
    <div class="card col-12">
        <div class="p-3">
            <form>
                <div class="row">
                    <div class="form-group col-md-3">
                        <label for="friendlyname">Friendly Name*</label>
                        <input type="text" class="form-control" id="friendlyname" placeholder="Enter Friendly Name">
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-3">
                        <label for="ipaddress">IP Address*</label>
                        <input type="text" class="form-control" id="ipaddress" placeholder="eg. 192.0.2.1">
                    </div>
                    <div class="form-group col-md-2">
                        <label for="port">Port</label>
                        <input type="text" class="form-control" id="port" value="22">
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-2">
                        <label for="netmikodriver">Netmiko Driver*</label>
                        <select class="form-control" id="netmikodriver">
                        </select>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-2">
                        <label for="users">User*</label>
                        <select class="form-control" id="users">
                        </select>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-3">
                        <label for="configcommand">Config Command</label>
                        <input type="text" class="form-control" id="configcommand" placeholder="eg. display current-configuration">
                        <small id="configcommand" class="form-text text-muted">Provide the command to gather running configuration if common commands are not viable. Eg show run, display config, etc...</small>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-3">
                        <label for="precommands">Pre Commands</label>
                        <textarea class="form-control" id="precommands" rows="3"></textarea>
                        <small id="precommands" class="form-text text-muted">Pre-commands will run before the "Config Command".</small>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-2">
                        <label for="groups">Group</label>
                        <select class="form-control" id="groups">
                            <option />
                        </select>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-3">
                        Description Placeholder Here
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-3">
                        Notes Placeholder Here
                    </div>
                </div>
                <input id="addDeviceBtn" class="btn btn-primary" type="submit" value="Add Device">
            </form>
        </div>
    </div>
</div>
<div class="container-fluid">
    <h5>Debug Output</h5>
    <pre class="bg-light p-3" id="debugOutput">
    </pre>
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{{ url_for('static', filename='js/devices/devices_add.js') }}"></script>
{% endblock %}

app/templates/groups/index.html
{% extends 'base.html' %}

{% block stylesheets %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-treeview.css') }}">
{% endblock %}

{% block content %}
<h1>Groups</h1>
<div class="row">
    <div class="col-5">
        <div class="card p-4 mb-5 h-100">
            <h5>Explorer</h5>
            <div id="groups_tree"></div>
        </div>
    </div>
    <div class="col-3">
        <div class="card p-4 mb-5">
            <h5>Create Folder</h5>
            <form>
                <div class="row">
                    <div class="form-group p-3">
                        <label for="folder_name">Folder</label>
                        <input type="text" class="form-control" id="folder_name" disabled>
                    </div>
                    <div class="form-group p-3">
                        <label for="folder_parent">Parent Folder</label>
                        <input type="text" class="form-control" id="folder_parent" disabled>
                    </div>
                </div>
                <div class="float-right">
                    <input id="addFolderBtn" class="btn btn-primary" type="submit" value="Create" disabled>
                    <input id="deleteFolderBtn" class="btn btn-danger" type="submit" value="Delete" disabled>
                </div>
            </form>
        </div>
    </div>
    <div class="col-4">
        <div class="card p-4 mb-5">
            <h5>Devices</h5>
            <table class="table table-striped" id="groupMemberTable">
                <thead>
                    <th>Members</th>
                </thead>
                <tbody>
                </tbody>
            </table>
            <form>
                <input id="addDeviceBtn" class="btn btn-primary" type="submit" value="Add Device" disabled>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap-treeview.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/groups/groups_generic.js') }}"></script>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="p-5">
    <h1>Dashboard</h1>
    <div class="row">
        <div class="col-sm-2">
            <div class="card">
                <div class="card-body text-center">
                    <h5 class="card-title">Current Devices</h5>
                    <div class="numberCircle">15</div>
                </div>
            </div>
        </div>
        <div class="col-sm-2">
            <div class="card">
                <div class="card-body text-center">
                    <h5 class="card-title">Current Users</h5>
                    <div class="numberCircle">3</div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/settings/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Settings</h1>
<div class="row m-3">
    <div class="card col-12">
        <div class="p-3">
            <form>
                <div class="row">
                    <div class="form-group col-md-3">
                        <label for="backupRootDir">Backup Root Directory</label>
                        <input type="text" class="form-control" id="backupRootDir" placeholder="Eg. backups">
                    </div>
                    <div id="additionalSettings">
                    </div>
                </div>
                <button id="editSettingsBtn" class="btn btn-primary"><i class="fas fa-lock p-1"></i>Edit</button>
                <button id="saveSettingsBtn" class="btn btn-primary"><i></i>Save</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{{ url_for('static', filename='js/settings/settings_generic.js') }}"></script>
{% endblock %}

app/templates/users/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Users</h1>
<div class="row m-3">
    <div class="card col-12">
        <div class="p-3">
            <table class="table table-striped" id="usersTable">
                <thead>
                    <th>#</th>
                    <th>Username</th>
                    <th>Password</th>
                    <th>Total Devices</th>
                </thead>
                <tbody>
                </tbody>
            </table>
            <div class="float-right">
                <form>
                    <div class="row">
                        <div class="form-group p-3">
                            <label for="username">Username</label>
                            <input type="text" class="form-control" id="username" placeholder="Enter Username">
                        </div>
                        <div class="form-group p-3">
                            <label for="password">Password</label>
                            <input type="password" class="form-control" id="password" placeholder="Enter Password">
                        </div>
                    </div>
                    <input id="addUserBtn" class="btn btn-primary" type="submit" value="Add User">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{{ url_for('static', filename='js/users/users_generic.js') }}"></script>
{% endblock %}